spring:
  rabbitmq:
    addresses: localhost:5672
    username: zoolye
    password: 123456
    virtual-host: /zool
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true

server:
  port: 6244